services:
  mongodb:
    image: mongo:6.0
    container_name: violet
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: violet
      MONGO_INITDB_ROOT_PASSWORD: violet
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
